name = "agame-party"
compatibility_date = "2024-09-01"
main = "./party/main.ts"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BuzzerServer"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PartyDurable"]

[[migrations]]
tag = "v3"
deleted_classes = ["BuzzerServer"]

[[migrations]]
tag = "v4"
renamed_classes = [{ from = "PartyDurable", to = "GameRoom" }]

[[durable_objects.bindings]]
name = "PARTYKIT_DURABLE"
class_name = "GameRoom"

[vars]
PARTYKIT_HOST = "agame-party.mateoamadoares.workers.dev"
